spring:
  data:
    mongodb:
      #iemss2019.com
      #uri: mongodb://localhost/WebsiteCheck

      #peianping.com
      host: 47.101.223.194
      port: 27017
      username: homepage
      password: 1qaz@wsx
      database: homepage



  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  mvc:
    static-path-pattern: /static/**

  mail:
    host: smtp.163.com
    username: nj_gis@163.com
    password: 1qaz2wsx
    default-encoding: UTF-8
    protocol: smtp
    port: 25
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true

managerEmail: 921485453@qq.com
watcherEmail: chenmin0902@163.com
    
